### ISSUE TITLE
Удаление теста

### ISSUE THREAD

**Issue by vpougatchev60** [olendeer/bha#11]
При выборе функции удаления теста появляется вот этот запрос:

![bha-web-04](https://user-images.githubusercontent.com/79328371/112200752-c6cf5d80-8bcc-11eb-8e56-993e12cb2216.png)

а должно быть как в п. 15.1 ТЗ.

Само удаление работает. Но после удаления профиль не обновляется - я удалил единственный в профиле тест, и после удаления его результаты остались на странице.

**Comment by olendeer** [comment]
Надпись в попапе поправил, по поводу обновления страницы, в данный момент сама страница пользователя очень сыра, т.к. есть много вопросов, которые следует обсудить, поэтому и попросил перенести реализацию профиля в третий этап работ, вместо чего выполнил пару пунктов из третьего этапа в этом, во втором. Обновление страницы после удаления теста тоже будет делать позже, т.к. пока что сам тест не выводится на странице

**Comment by olendeer** [comment]
Доработано
