### ISSUE TITLE
Редактирование комментария

### ISSUE THREAD

**Issue by vpougatchev60** [olendeer/bha#12]
Есть две проблемы:

1. После добавления или изменения текущего комментария соответствующее поле на экране не обновляется.
2. Если у тесту уже есть комментарий, то при выборе функции редактирования комментария его текущее содержимое должно заполнить поле формы для редактирования.

**Comment by olendeer** [comment]
Исправил

**Comment by vpougatchev60** [comment]
Исправление подтверждено.
