### ISSUE TITLE
Сообщение об успешной регистрации

### ISSUE THREAD

**Issue by vpougatchev60** [olendeer/bha#4]
После успешной регистрации нового пользователя должно появиться сообщение:

“A new account was successfully created. Check your mailbox registered with the account to confirm the account activation.”

Что-то появляется буквально на мгновение, так что невозможно разглядеть что это. Если это какой-то попап, то нужно, чтобы он задерживался на экране секунд на 5.

**Comment by olendeer** [comment]
fixed
