### ISSUE TITLE
После Logout портятся поля страницы авторизации

### ISSUE THREAD

**Issue by vpougatchev60** [olendeer/bha#6]
После успешной авторизации делаю логаут и получаю страницу авторизации, поля которой испорчены заполненными ранее данными. Нужно либо блокировать автоматическую подстановку этих данных, либо они должны подставляться в правильном визуальном формате как при вводе вручную.
![bha-web-01](https://user-images.githubusercontent.com/79328371/112192150-f29a1580-8bc3-11eb-9396-3e01c544ae28.png)

**Comment by olendeer** [comment]
Исправил

**Comment by vpougatchev60** [comment]
Исправление подтверждено.
