### ISSUE TITLE
В форме создания нового клиента портятся поля ввода имени пользователя и пароля

### ISSUE THREAD

**Issue by vpougatchev60** [olendeer/bha#7]
При открытии формы создания нового клиента поля username и password автоматически заполняются значениями, введенными при логине и их дизайн искажается. Нужно предотвращать такое заполнение.
![bha-web-02](https://user-images.githubusercontent.com/79328371/112193050-b9ae7080-8bc4-11eb-87f5-446c85df7cd5.png)

**Comment by olendeer** [comment]
Исправил

**Comment by vpougatchev60** [comment]
Исправление подтверждено.
