### ISSUE TITLE
Подправить формат названий показателей в профиле клиента

### ISSUE THREAD

**Issue by vpougatchev60** [olendeer/bha#8]
На странице профиля клиента нужно обеспечить единообразие в названиях всех показателей. Нужно чтобы все слова начинались с большой буквы.

Там же нужно будет реализовать правильное отображение значений на шкалах графиков Body Adaptation и Heart Rate. Если пока этот функционал еще не реализован, то обратим внимание на это позже.
![bha-web-03](https://user-images.githubusercontent.com/79328371/112196975-cd5bd600-8bc8-11eb-8202-1d016b6eb260.png)

**Comment by olendeer** [comment]
Это ещё в процессе обсуждения и реализации, будет во в третьей части

**Comment by olendeer** [comment]
Делалось всё по макету, там именно всё так как сейчас, но если нужно - то сделаю единообразие в названиях

**Comment by vpougatchev60** [comment]
Да, единообразие в названиях, хоть и мелочь, но есть признак профессиональности продукта с точки зрения пользователя.
