### ISSUE TITLE
Генерация Excel отчета

### ISSUE THREAD

**Issue by vpougatchev60** [olendeer/bha#9]
При попытке открыть созданный Excel документ выдается такое сообщение:

![image](https://user-images.githubusercontent.com/79328371/112197820-b8337700-8bc9-11eb-893e-150a93386dc9.png)

А если продолжить и открыть, то в документе обнаруживается одна таблица, в которой только:

![image](https://user-images.githubusercontent.com/79328371/112198001-e9ac4280-8bc9-11eb-8c48-460dfea3cc87.png)

**Comment by olendeer** [comment]
Хмм.., у меня excel открывал нормально файл, так мало полей потому что отчет генерируется пока что по последнему тесту, в этом случае вам пришел отчет Body measurements(кажется), и в нем только эти поля. В данный момент не реализовано переключение между тестами, это будет делаться в третьей части работ, после детального обсуждения. попробуйте зайти к другому пользователю, и сгенерить отчет по нему

**Comment by vpougatchev60** [comment]
Какая у вас версия Excel, которой открываете файл. У меня - Office 2013. Может вы генерите файл в формате XLSX, а сохраняете как XLS?

**Comment by olendeer** [comment]
Завтра проверю ещё раз

**Comment by olendeer** [comment]
Исправлено

**Comment by olendeer** [comment]
Доработано
